name: PR Validate

on:
  workflow_call:
    inputs:
      ### Typical / recommended
      conventional_commits:
        description: 'Enforce conventional commits?'
        required: false
        type: string
      markdown_links:
        description: 'Links for PR description'
        required: false
        type: string

jobs:
  conventional-commits:
    name: Conventional Commits
    if: inputs.conventional_commits != 'false'
    runs-on: ubuntu-22.04
    steps:
      - uses: amannn/action-semantic-pull-request@v5.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: failure()
        run: |
          echo "Please use conventional commits in your PR title and re-run this job."
          echo "https://www.conventionalcommits.org/en/v1.0.0/"
          exit 1

  description:
    name: Description
    if: inputs.markdown_links != ''
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: bcgov-nr/action-pr-description-add@v1.1.1
        env:
          DOMAIN: apps.silver.devops.gov.bc.ca
          PREFIX: ${{ github.event.repository.name }}
        with:
          add_markdown: |
            ---

            Thanks for the PR!

            Deployments, as required, will be available below:
            ${{ inputs.markdown_links }}

            Please create PRs in draft mode.  Mark as ready to enable:
            - [Analysis Workflow](https://github.com/${{ github.repository }}/actions/workflows/analysis.yml)

            After merge, new images are deployed in:
            - [Merge Workflow](https://github.com/${{ github.repository }}/actions/workflows/merge.yml)
