name: Build Packages

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Specify a tag to build; defaults to latest'
        default: latest
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  # https://github.com/bcgov-nr/action-builder-ghcr
  builds:
    name: Builds
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [migrations, backend, frontend]
    timeout-minutes: 10
    steps:
      - uses: bcgov/action-builder-ghcr@d63c76a4bb7914d3a986a035904b49d99c2c4613 # v3.0.0
        id: builds
        with:
          keep_versions: 50
          package: ${{ matrix.package }}
          repository: bcgov/quickstart-openshift
          tag: ${{ inputs.tag }}
