name: PR Closed

on:
  pull_request:
    types: [closed]

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: pr-${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  cleanup:
    name: Cleanup OpenShift and/or Promote Images
    uses: ./.github/workflows/.pr-close.yml
    secrets: inherit
    with:
      cleanup: helm
      packages: backend frontend migrations
      tag_promote: latest
