name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    # uses: bcgov-nr/action-support/.github/workflows/pr-close.yml@main
    uses: ./.github/workflows/.pr-close.yml
