name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  pr-close:
    name: Close
    uses: ./.github/workflows/.pr-close.yml

  pr-validate:
    name: Validate
    needs: pr-close
    uses: ./.github/workflows/.pr-validate.yml
    with:
      conventional_commits: false
      # markdown_links: |
      #   - [Frontend](https://${{ github.event.repository.name }}-${{ github.event.number }}-frontend.apps.silver.devops.gov.bc.ca)
      #   - [Backend](https://${{ github.event.repository.name }}-${{ github.event.number }}-frontend.apps.silver.devops.gov.bc.ca/api)
