name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  pr-validate:
    name: Validate
    uses: ./.github/workflows/.pr-validate.yml
    with:
      markdown_links: |
        - [Frontend](https://${{ github.event.repository.name }}-${{ github.event.number }}-frontend.apps.silver.devops.gov.bc.ca)
        - [Backend](https://${{ github.event.repository.name }}-${{ github.event.number }}-frontend.apps.silver.devops.gov.bc.ca/api)

  # https://github.com/bcgov-nr/action-builder-ghcr
  builds:
    name: Builds
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package: [migrations, backend, frontend]
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.0.2
        id: builds
        with:
          keep_versions: 50
          package: ${{ matrix.package }}
          repository: bcgov/quickstart-openshift
          tag: ${{ github.event.number }}
          tag_fallback: latest
          triggers: ('${{ matrix.package }}/')

  deploys:
    name: Deploys
    needs: [builds]
    uses: ./.github/workflows/.deployer.yml
    secrets: inherit
    with:
      params: --set global.autoscaling=false --set Chart.name=${{ github.event.repository.name }} #--set Chart.version=${{ github.event.number }}
      release: ${{ github.event.number }}

  pr-close:
    name: Close
    needs: [deploys]
    uses: ./.github/workflows/.pr-close.yml
    with:
      cleanup: helm
