name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  # pr-close:
  #   name: PR Close
  #   uses: ./.github/workflows/.pr-close.yml

  pr-validate:
    name: PR Validate
    uses: ./.github/workflows/.pr-validate.yml

