name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/.pr-validate.yml
    with:
      markdown_links: |
        - [Frontend](https://${{ github.event.repository.name }}-${{ github.event.number }}-frontend.apps.silver.devops.gov.bc.ca)
        - [Backend](https://${{ github.event.repository.name }}-${{ github.event.number }}-frontend.apps.silver.devops.gov.bc.ca/api)

  # Retags, meant to look like builds
  builds:
    name: Fake Builds
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package: [migrations, backend, frontend]
    timeout-minutes: 1
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: latest
          tags: ${{ github.event.number }}

  deploys:
    name: Deploys
    needs: [builds]
    uses: ./.github/workflows/.deployer.yml
    secrets:
      oc_namespace: ${{ secrets.oc_namespace }}
      oc_token: ${{ secrets.oc_token }}
    with:
      params: --set global.autoscaling=false

  # close:
  #   name: Close
  #   needs: [deploys]
  #   uses: ./.github/workflows/.pr-close.yml
  #   secrets:
  #     oc_namespace: ${{ secrets.oc_namespace }}
  #     oc_token: ${{ secrets.oc_token }}
  #   with:
  #     cleanup: helm

  # results:
  #   name: PR Results
  #   needs: [validate, deploys, close]
  #   if: always() && !failure()
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - run: echo "Workflow completed successfully!"
